name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build
        env:
          VITE_SUPABASE_URL: https://vdgvncfujtfnnwmimtry.supabase.co
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZ3ZuY2Z1anRmbm53bWltdHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMDg3MDMsImV4cCI6MjA4OTU4NDcwM30.u_5VTYmvCnykeFQj-nU6rvxLOdSHVfcsfhdnHM9h6dc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
